"""new fields body_embeddings_raw and face_embeddings_raw added

Revision ID: 124218570913
Revises: 82abb85cf3c0
Create Date: 2025-12-26 17:35:24.333384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '124218570913'
down_revision: Union[str, Sequence[str], None] = '82abb85cf3c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_events')
    op.add_column('users', sa.Column('body_embeddings_raw', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('face_embeddings_raw', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'face_embeddings_raw')
    op.drop_column('users', 'body_embeddings_raw')
    op.create_table('person_events',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('camera_src', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('person_events_pkey'))
    )
    # ### end Alembic commands ###
