"""new tables camera and camera_category

Revision ID: 2b352a24aed1
Revises: bf5572a81a40
Create Date: 2025-12-23 16:49:15.871038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b352a24aed1'
down_revision: Union[str, Sequence[str], None] = 'bf5572a81a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_camera_category_id'), 'camera_category', ['id'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_name', sa.String(), nullable=False),
    sa.Column('camera_number', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['camera_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_number')
    )
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.drop_index(op.f('ix_embeddings_user_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.add_column('users', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_users_body_embedding_ivfflat'), table_name='users', postgresql_ops={'body_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_users_face_embedding_ivfflat'), table_name='users', postgresql_ops={'face_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_foreign_key(None, 'users', 'camera_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index(op.f('ix_users_face_embedding_ivfflat'), 'users', ['face_embedding'], unique=False, postgresql_ops={'face_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_users_body_embedding_ivfflat'), 'users', ['body_embedding'], unique=False, postgresql_ops={'body_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('users', 'category_id')
    op.create_table('embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('ts', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cam_idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('frame_idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('det_idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('x1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('y1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('x2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('y2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('embedding_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('embedding_dim', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('embedding_norm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('embedding', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('embeddings_pkey'))
    )
    op.create_index(op.f('ix_embeddings_user_id'), 'embeddings', ['user_id'], unique=False)
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_camera_category_id'), table_name='camera_category')
    op.drop_table('camera_category')
    # ### end Alembic commands ###
