"""camera number removed from camera table

Revision ID: 2dbf474a7a8b
Revises: fb99a5e9bbd4
Create Date: 2025-12-30 11:21:50.654663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dbf474a7a8b'
down_revision: Union[str, Sequence[str], None] = 'fb99a5e9bbd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cameras_camera_number_key'), 'cameras', type_='unique')
    op.drop_column('cameras', 'camera_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('camera_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('cameras_camera_number_key'), 'cameras', ['camera_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
