"""data type changed from largebytes to LargeBinary for body_embeddings_raw and face_embeddings_raw added

Revision ID: 64c7ca7a5fbd
Revises: 124218570913
Create Date: 2025-12-26 17:44:56.117245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c7ca7a5fbd'
down_revision: Union[str, Sequence[str], None] = '124218570913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
