"""add gender to users

Revision ID: ad77708d2c31
Revises: 402f66948513
Create Date: 2026-01-08 12:25:58.779767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad77708d2c31'
down_revision: Union[str, Sequence[str], None] = '402f66948513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_camera_area_definition_id'), table_name='camera_area_definition')
    op.drop_table('camera_area_definition')
    op.drop_index(op.f('ix_camera_category_id'), table_name='area_definition')
    op.create_index(op.f('ix_area_definition_id'), 'area_definition', ['id'], unique=False) 
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.alter_column('users', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'gender') 
    op.drop_index(op.f('ix_area_definition_id'), table_name='area_definition')
    op.create_index(op.f('ix_camera_category_id'), 'area_definition', ['id'], unique=False)
    op.create_table('camera_area_definition',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('camera_area_definition_pkey')),
    sa.UniqueConstraint('name', name=op.f('camera_area_definition_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_camera_area_definition_id'), 'camera_area_definition', ['id'], unique=False)
    # ### end Alembic commands ###
