"""removed date_time & event listener removed for update time_spent

Revision ID: bf5572a81a40
Revises: d586ea602214
Create Date: 2025-12-16 13:20:42.751681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf5572a81a40'
down_revision: Union[str, Sequence[str], None] = 'd586ea602214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_presence', 'time_spent')
    op.drop_column('user_presence', 'date_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_presence', sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user_presence', sa.Column('time_spent', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
