"""camera number removed from camera table

Revision ID: fb99a5e9bbd4
Revises: 6eb2192cef57
Create Date: 2025-12-30 11:18:18.250017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb99a5e9bbd4'
down_revision: Union[str, Sequence[str], None] = '6eb2192cef57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
